import type { PieceType } from '../engine'

export const hexTrainingProfile = {
  name: 'hex-self-play-v1',
  seed: 20260608,
  simulatedGames: 2400,
  maxPlies: 90,
  notes: [
    '自博弈样本混合普通棋局、护盾局、传送门局、能量快启动局和特殊走法局。',
    '权重偏向能量转化、技能可用性、护盾交换价值、传送门控制和将军威胁。',
    '仍保留传统子力价值作为底盘，避免为了技能收益乱弃大子。',
  ],
  pieceValue: {
    general: 10000,
    chariot: 930,
    cannon: 470,
    horse: 430,
    elephant: 230,
    advisor: 230,
    soldier: 125,
  } satisfies Record<PieceType, number>,
  feature: {
    shield: 72,
    energy: 31,
    lowEnergyBonus: 18,
    activeRuneReady: 94,
    activeRuneNearReady: 35,
    passiveRuneStrength: 18,
    coreAugment: 86,
    mobility: 3.4,
    captureThreat: 0.16,
    checkGiven: 340,
    checkTaken: -460,
    portalControl: 42,
    portalMobility: 18,
    palaceGuard: 22,
    advancedSoldier: 44,
    riverSoldier: 24,
    cannonScreen: 26,
    protectedMajor: 38,
  },
  coreValue: {
    'chrono-storm': 175,
    'river-reactor': 135,
    'quantum-anchor': 190,
    'arcane-tithe': 130,
    'golden-aegis': 115,
    'singularity-gates': 155,
    'great-wall-beacons': 105,
    'hundred-schools': 155,
    'royal-road': 145,
    'warring-states': 120,
    dujiangyan: 160,
    'well-field-system': 145,
    'crossbow-commandery': 165,
    'yumen-pass': 130,
    'imperial-arsenal': 125,
    'nine-province-map': 140,
  } as Record<string, number>,
}

export type HexTrainingProfile = typeof hexTrainingProfile
